run: |
        python -m PyInstaller --noconsole --onefile `
        --add-data "soundeffects;soundeffects" `
        --add-data "soundtrack;soundtrack" `
        --add-data "sprites;sprites" `
        main.py